spring.application.name=otpservice

server.port=${PORT:8080}


# frontend url
frontend.url=${FRONTEND_URL}


# --------otp----
# Gmail's server for sending mail
spring.mail.host=smtp.gmail.com
# TLS port used for secure mail
spring.mail.port=587
# Gmail login
spring.mail.username=${EMAIL_FOR_OTP}

# app password
spring.mail.password=${PASSWORD_FOR_OTP}

# Tells gamil we are logging in with creadentials
spring.mail.properties.mail.smtp.auth=true
# Enable encryption for security
spring.mail.properties.mail.smtp.starttls.enable=true

